```{r}
library(dplyr)
library(corrplot)
library(glmnet)
#library(countrycode)
library(data.table)
library(tidyverse)
```
```{r}
setwd("D:/5th_Sem_pdfs/Data_Analytics/Ajeya_Data-Analytics/fifa-20-complete-player-dataset")
data_19=read.csv("players_19.csv")
#data_19 <-data_19 %>% na.omit()
data_18=read.csv("players_18.csv")
#data_18 <-data_18 %>% na.omit()
data_17=read.csv("players_17.csv")
#data_17 <-data_17 %>% na.omit()
data_16=read.csv("players_16.csv")
#data_16 <-data_16 %>% na.omit()
data_20=read.csv("players_20.csv")
#data_20 <-data_20 %>% na.omit()

data_val$v16=data_16$value_eur
data_val$v17=data_17$value_eur
data_val$v18=data_18$value_eur
data_val$v19=data_19$value_eur
data_val$v20=data_20$value_eur
```

```{r}
data_19$ID<-NULL
data_19$player_url <- NULL
data_19$dob <- NULL
data_19$real_face <- NULL
data_19$player_traits <- NULL
data_19$long_name <- NULL
data_19$player_tags <- NULL
data_19$body_type <- NULL
data_19 <- data_19 %>% filter(data_19$value_eur!=0 )
data_19_high=subset(data_19,overall>69)
data_19_low=subset(data_19,overall<=69)
data_19$player_positions=as.character(data_19$player_positions)
data_19$primary_position <- map(data_19$player_positions,function(x) trimws(unlist(strsplit(x,',')))[1])
data_19$primary_position <- unlist(data_19$primary_position)
```


```{r}
#new column for grouping a player based on which part of the field he plays
data_19$pos=data_19$primary_position
for(i in 1:nrow(data_19)){
  if(data_19[i,]$primary_position=="ST" | data_19[i,]$primary_position=="LW" | data_19[i,]$primary_position=="RW" | data_19[i,]$primary_position=="CF" | data_19[i,]$primary_position=="RF" | data_19[i,]$primary_position=="LF" | 
     data_19[i,]$primary_position=="RS" |data_19[i,]$primary_position=="LS" ){
    data_19[i,]$pos="Forward"
  }
  if(data_19[i,]$primary_position=="CM" |data_19[i,]$primary_position=="LM" |data_19[i,]$primary_position=="LDM" |data_19[i,]$primary_position=="RM" |data_19[i,]$primary_position=="CDM" |data_19[i,]$primary_position=="CAM" |data_19[i,]$primary_position=="RDM" |data_19[i,]$primary_position=="LAM" |data_19[i,]$primary_position=="RAM" |data_19[i,]$primary_position=="LCM" |data_19[i,]$primary_position=="RCM" ){
    data_19[i,]$pos="Midfielder"
  }
  if(data_19[i,]$primary_position=="LCB" |data_19[i,]$primary_position=="RCB" |data_19[i,]$primary_position=="LWB" |data_19[i,]$primary_position=="RWB" |
     data_19[i,]$primary_position=="LB" |data_19[i,]$primary_position=="CB" |data_19[i,]$primary_position=="RB" ){
    data_19[i,]$pos="Back"
  }
  if(data_19[i,]$primary_position=="GK" ){
    data_19[i,]$pos="Keeper"
  }
}
#primary position column having the players'best/favourite position
data_19_strikers <- data_19 %>% filter(data_19$primary_position %in% c("ST","RW","LW","CF","RF","LF","RS","LS"))
data_19_midfielders <-  data_19 %>% filter(data_19$primary_position %in% c("RCM","LCM","CM","LM","RM","CDM","LDM","RDM","LAM","CAM","RAM"))
data_19_defenders <- data_19 %>% filter(data_19$primary_position %in% c("CB","LB","RB","RCB","LCB","RWB","LWB"))
data_19_goalkeepers <- data_19 %>% filter(data_19$primary_position %in% c("GK"))
q <- colnames(data_19_defenders)

#separate dataframes created for each role
q <- grep("^gk_+",q,value = TRUE)
p <- c("pace","shooting","passing","dribbling","defending","physic")
data_19_strikers <- data_19_strikers[,!names(data_19_strikers) %in% q]
data_19_defenders <- data_19_defenders[,!names(data_19_defenders) %in% q]
data_19_midfielders <- data_19_midfielders[,!names(data_19_midfielders) %in% q]
data_19_goalkeepers <- data_19_goalkeepers[,!names(data_19_goalkeepers) %in% p]
data_19_strikers$position<-"F"
data_19_defenders$position<-"B"
data_19_midfielders$position<-"M"
data_19_goalkeepers$position<-"K"
#The columns which have gk attributes have been set to NULL for players who are not goalkeepers, and the attributes which do not matter for a goalkeeper have been set to  NULL for players who are not goalkeepers.
```

```{r}

#stripcharts of target value vs various attributes
par(mfrow=c(2,3))
stripchart(v16/1000000,data_val,vertical=TRUE,cex=0.9,main="Stripchart of year 2016 vs market value",ylab="Market value in million euros")
stripchart(v17/1000000,data_val,vertical=TRUE,cex=0.9,main="Stripchart of year 2017 vs market value",ylab="Market value in million euros")
stripchart(v18/1000000,data_val,vertical=TRUE,cex=0.9,main="Stripchart of year 2018 vs market value",ylab="Market value in million euros")
stripchart(v19/1000000,data_val,vertical=TRUE,cex=0.9,main="Stripchart of year 2019 vs market value",ylab="Market value in million euros")
stripchart(v20/1000000,data_val,vertical=TRUE,cex=0.9,main="Stripchart of year 2020 vs market value",ylab="Market value in million euros")
par(mfrow=c(1,1))
stripchart(value_eur/1000000~pos,data_19,vertical=TRUE,cex=0.9,main="Stripchart of position vs market value",ylab="Market value in million euros",xlab="position")
stripchart(value_eur/1000000~age,data_19,vertical=TRUE,cex=0.9,main="Stripchart of age vs market value",ylab="Market value in million euros",xlab="age")
stripchart(value_eur/1000000~international_reputation,data_19,vertical=TRUE,cex=0.9,main="Stripchart of player's international reputation vs market value",ylab="Market value in million euros",xlab="international reputation")
stripchart(value_eur/1000000~work_rate,data_19,vertical=TRUE,cex=0.9,main="Stripchart of player's work rate vs market value",ylab="Market value in million euros",xlab="work rate",cex.axis=0.5)
stripchart(value_eur/1000000~shooting,data_19_strikers,vertical=TRUE,cex=0.9,main="Stripchart of a forward's shooting ability vs market value",ylab="Market value in million euros",xlab="Shooting rating")
stripchart(value_eur/1000000~defending,data_19_defenders,vertical=TRUE,cex=0.9,main="Stripchart of a defender's defending ability vs market value",ylab="Market value in million euros",xlab="Defending rating")
stripchart(value_eur/1000000~dribbling,data_19_midfielders,vertical=TRUE,cex=0.9,main="Stripchart of a midfielder's dribbling ability vs market value",ylab="Market value in million euros",xlab="Dribbling rating")
stripchart(value_eur/1000000~gk_reflexes,data_19_goalkeepers,vertical=TRUE,cex=0.9,main="Stripchart of a goalkeeper's reflex ability vs market value",ylab="Market value in million euros",xlab="reflex rating")
stripchart(value_eur/1000000~attacking_crossing,data_19_strikers,vertical=TRUE,cex=0.9,main="Stripchart of a forward's attacking crossing vs market value",ylab="Market value in million euros",xlab="reflex rating")
stripchart(value_eur/1000000~attacking_finishing,data_19_strikers,vertical=TRUE,cex=0.9,main="Stripchart of a forward's attacking finishing vs market value",ylab="Market value in million euros",xlab="reflex rating")
stripchart(value_eur/1000000~attacking_heading_accuracy,data_19_strikers,vertical=TRUE,cex=0.9,main="Stripchart of a forward's attacking heading accuracy vs market value",ylab="Market value in million euros",xlab="reflex rating")
stripchart(value_eur/1000000~attacking_short_passing,data_19_midfielders,vertical=TRUE,cex=0.9,main="Stripchart of a midfielder's attacking short passing vs market value",ylab="Market value in million euros",xlab="reflex rating")
stripchart(value_eur/1000000~skill_dribbling,data_19_midfielders,vertical=TRUE,cex=0.9,main="Stripchart of a midfielder's skill dribbling vs market value",ylab="Market value in million euros",xlab="reflex rating")
stripchart(value_eur/1000000~short_passing,data_19_strikers,vertical=TRUE,cex=0.9,main="Stripchart of a forward's short passing vs market value",ylab="Market value in million euros",xlab="reflex rating")

stripchart(value_eur/1000000~passing,data_19_midfielders,vertical=TRUE,cex=0.9,main="Stripchart of a midfielder's passing ability vs market value",ylab="Market value in million euros",xlab="Passing rating")
stripchart(value_eur/1000000~passing,data_19_strikers,vertical=TRUE,cex=0.9,main="Stripchart of a forward's passing vs market value",ylab="Market value in million euros",xlab="Passing rating")
stripchart(value_eur/1000000~physic,data_19_defenders,vertical=TRUE,cex=0.9,main="Stripchart of a defender's physicality vs market value",ylab="Market value in million euros",xlab="Physical rating")
stripchart(value_eur/1000000~gk_diving,data_19_goalkeepers,vertical=TRUE,cex=0.9,main="Stripchart of a goalkeeper's diving ability vs market value",ylab="Market value in million euros",xlab="Diving rating")

```
